dist: trusty
sudo: false  # Use the new travis docker based infrastructure
# We always want to be able to reach a tagged version in `git describe`
git:
  depth: 99999

language: python
python:
- '3.6'

cache:
  directories:
  - $HOME/.cache/pip
addons:
  postgresql: '9.6'
  apt:
      sources:
      - sourceline: ppa:nextgis/ppa
      packages:
          - gdal-bin
          - gdal-data
          - libhdf5-serial-dev
          - libnetcdf-dev
          - libproj-dev
          - libgdal1-dev
          - libgdal-dev
          - libgdal1h
          - libgdal20
          - libudunits2-dev
          - libblas-dev
          - liblapack-dev
          - gfortran
          - libudunits2-0
          - postgresql-9.6-postgis-2.3
before_install:
# Database for the integration tests.
- createdb dea_integration
# Tests should never use the default datacube config, so add a "honeypot" that fails.
- cp .travis/honeypot.conf ~/.datacube.conf

- export CPLUS_INCLUDE_PATH="/usr/include/gdal"
- export C_INCLUDE_PATH="/usr/include/gdal"
- export LD_LIBRARY_PATH="/usr/lib:/usr/lib/postgresql/9.6/lib:$LD_LIBRARY_PATH"
- sudo updatedb
- locate libgdal
- travis_retry pip install --upgrade pip
- travis_retry pip install --progress-bar off coveralls codecov
- travis_retry pip install --progress-bar off --requirement requirements-test.txt
- travis_retry pip install -e git+https://github.com/opendatacube/datacube-core.git#egg=datacube
- travis_retry pip install -e git+https://github.com/GeoscienceAustralia/eo-datasets.git#egg=eodatasets
- travis_retry pip install -e git+https://github.com/GeoscienceAustralia/digitalearthau.git#egg=digitalearthau
install:
- travis_retry pip install .[test] --upgrade
- pip freeze
script:
- ./check-code.sh integration_tests --cov cubedash
